# Generated by Django 5.2.5 on 2025-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtrack',
            name='tracks',
            field=models.CharField(choices=[('DS', 'Data Science'), ('DA', 'Data Analysis'), ('FE', 'FrontEnd'), ('BE', 'BackEnd')], default='DS', max_length=4, verbose_name='Tracks'),
        ),
    ]
