# Generated by Django 5.2.5 on 2025-08-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_jobtrack_tracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('DS', 'Data Science'), ('DA', 'Data Analysis'), ('FE', 'FrontEnd'), ('BE', 'BackEnd')], default='DS', max_length=4, verbose_name='Track')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('DS', 'Data Science'), ('DA', 'Data Analysis'), ('FE', 'FrontEnd'), ('BE', 'BackEnd')], default='DS', max_length=4, verbose_name='Chosen Track')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='skills',
            name='job_track',
        ),
        migrations.DeleteModel(
            name='JobTrack',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
