# Generated by Django 5.2.5 on 2025-08-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_userinput_remove_skills_job_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='track',
            field=models.CharField(choices=[('DS', 'Data Science'), ('DA', 'Data Analysis'), ('FE', 'FrontEnd'), ('BE', 'BackEnd')], default='DS', max_length=30, verbose_name='Track'),
        ),
    ]
