# Generated by Django 5.2.5 on 2025-08-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skill_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='track',
            field=models.CharField(choices=[('DS', 'Data Science'), ('DA', 'Data Analysis'), ('FE', 'FrontEnd'), ('BE', 'BackEnd')], default='DS', max_length=100, verbose_name='Chosen Track'),
        ),
    ]
